/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphaneyonetim;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author yigit
 */

public class girisEkrani extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
//PreparedStatement pst;
JFrame frame = new JFrame("JOptionPane showMessageDialog example");

    /**
     * Creates new form girisEkrani
     */
/*
    public girisEkrani() {
        super ("Giris");
        initComponents();
        conn=baglanti.ConnecrDB();
    }*/
    
     public girisEkrani() {
         //setExtendedState(JFrame.MAXIMIZED_BOTH);  //tam ekran yapma kodu
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kimlikNoLBL = new javax.swing.JLabel();
        sifreLBL = new javax.swing.JLabel();
        kimlikNoTXT = new javax.swing.JTextField();
        sifreTXT = new javax.swing.JPasswordField();
        girisYapBtn = new javax.swing.JButton();
        uyeOlBtn = new javax.swing.JButton();
        sifremiUnuttumBtn = new javax.swing.JButton();
        sikayetBtn = new javax.swing.JButton();
        baslik = new javax.swing.JLabel();
        adminGirisBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kimlikNoLBL.setText("TC Kimlik No:");

        sifreLBL.setText("Şifre:");

        kimlikNoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kimlikNoTXTActionPerformed(evt);
            }
        });

        girisYapBtn.setText("Giriş Yap");
        girisYapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisYapBtnActionPerformed(evt);
            }
        });

        uyeOlBtn.setText("Üye Ol");
        uyeOlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeOlBtnActionPerformed(evt);
            }
        });

        sifremiUnuttumBtn.setText("Şifremi Unuttum");
        sifremiUnuttumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifremiUnuttumBtnActionPerformed(evt);
            }
        });

        sikayetBtn.setText("Şikayetleriniz/Önerileriniz");
        sikayetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sikayetBtnActionPerformed(evt);
            }
        });

        baslik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        baslik.setText("Hoşgeldiniz");

        adminGirisBtn.setText("Admin Girişi");
        adminGirisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminGirisBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baslik)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sifremiUnuttumBtn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(uyeOlBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                            .addComponent(girisYapBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kimlikNoLBL)
                                .addComponent(sifreLBL))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(kimlikNoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(sifreTXT))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sikayetBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminGirisBtn)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(baslik)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kimlikNoLBL)
                    .addComponent(kimlikNoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreLBL)
                    .addComponent(sifreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girisYapBtn)
                    .addComponent(uyeOlBtn))
                .addGap(23, 23, 23)
                .addComponent(sifremiUnuttumBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sikayetBtn)
                    .addComponent(adminGirisBtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sifremiUnuttumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifremiUnuttumBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        sifremiUnuttum sU=new sifremiUnuttum();
        sU.setVisible(true);      
    }//GEN-LAST:event_sifremiUnuttumBtnActionPerformed
   
    private void uyeOlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeOlBtnActionPerformed
    new uyeOlmaEkrani().setVisible(true);
    dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_uyeOlBtnActionPerformed

    private void girisYapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisYapBtnActionPerformed
    String kimlikNo=kimlikNoTXT.getText();
    String sifre=sifreTXT.getText();
    int hataKontrol=3;
    int hataKontrol2=3;
    uyeKutuphanesi uK = new uyeKutuphanesi();
   
    //String sqlAd1 = "SELECT * FROM kullanici WHERE kimlikNo='"+kimlikNo+"' and sifre='"+sifre+"';";
    //String sqlAd2 = 
    
       // Class.forName("com.oracle.jdbc.Driver");
        //Class.forName("oracle.jdbc.driver.OracleDriver");
       // Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","ygt","yigit");
        Connection con=baglanti.getConnection();
       // st.executeUpdate("SELECT * FROM kullanici WHERE kimlikNo='"+kimlikNo+"' and sifre='"+sifre+"';");
       // st.executeUpdate("SELECT * FROM kullanici;");
       // pst.getConnection().prepareStatement(sqlAd);
       String sqlAd = ("SELECT * FROM YGT.kullanici WHERE kimlikNo=? and sifre=?");
     uK.setVisible(true);
    
// TODO add your handling code here:
    }//GEN-LAST:event_girisYapBtnActionPerformed

    private void sikayetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sikayetBtnActionPerformed
    sikayetlerSayfa sS = new sikayetlerSayfa();
    sS.setVisible(true);
    dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_sikayetBtnActionPerformed

    private void kimlikNoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kimlikNoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kimlikNoTXTActionPerformed

    private void adminGirisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminGirisBtnActionPerformed
    adminGiris aG = new adminGiris();
    aG.setVisible(true);
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_adminGirisBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisEkrani().setVisible(true);
            }
        });
    }
    
    
    
    /*try 
        {
            //Connection con=baglanti.getConnection();
            //Statement st = con.createStatement();
            pst=conn.prepareStatement(sqlAd);
            pst.setString(1, kimlikNoTXT.getText());
            pst.setString(2, sifreTXT.getText());
            rs=pst.executeQuery();
            if(rs.next())
            {
                rs.close();
                pst.close();
                setVisible(false);
                uyeKutuphanesi uK = new uyeKutuphanesi();
                uK.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "yanlış giriş");
            }
        } 
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
        finally
        {
            try
            {
            rs.close();
            pst.close();
            }
            
            catch(Exception e)
                    {
                        System.out.println("olmadı abi");
                    }
        }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminGirisBtn;
    private javax.swing.JLabel baslik;
    private javax.swing.JButton girisYapBtn;
    private javax.swing.JLabel kimlikNoLBL;
    private javax.swing.JTextField kimlikNoTXT;
    private javax.swing.JLabel sifreLBL;
    private javax.swing.JPasswordField sifreTXT;
    private javax.swing.JButton sifremiUnuttumBtn;
    private javax.swing.JButton sikayetBtn;
    private javax.swing.JButton uyeOlBtn;
    // End of variables declaration//GEN-END:variables
}
