/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphaneyonetim;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yigit
 */
public class sikayetlerSayfa extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form sikayetlerSayfa
     */
    public sikayetlerSayfa() {
        super("Şikayet Sayfası");
        initComponents();
        conn=baglanti.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sikayetScroll = new javax.swing.JScrollPane();
        sikayetTXT = new javax.swing.JTextArea();
        gonderBtn = new javax.swing.JButton();
        geriDonBtn = new javax.swing.JButton();
        baslik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sikayetTXT.setColumns(20);
        sikayetTXT.setRows(5);
        sikayetScroll.setViewportView(sikayetTXT);

        gonderBtn.setText("Gönder");
        gonderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gonderBtnActionPerformed(evt);
            }
        });

        geriDonBtn.setText("Geri Dön");
        geriDonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonBtnActionPerformed(evt);
            }
        });

        baslik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        baslik.setText("Şikayet/Öneri Sayfası");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baslik)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(geriDonBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gonderBtn))
                        .addComponent(sikayetScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(baslik)
                .addGap(18, 18, 18)
                .addComponent(sikayetScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gonderBtn)
                    .addComponent(geriDonBtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriDonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonBtnActionPerformed
        dispose();
        girisEkrani gE = new girisEkrani();
        gE.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_geriDonBtnActionPerformed

    private void gonderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gonderBtnActionPerformed
        String sikayet=sikayetTXT.getText();
        if(sikayet.length()>2000)
        {
            System.out.println("Lütfen 2000 karakterden daha olacak şekilde şikayetinizi kısaltın veya parça parça göndermeyi deneyin");
        }
        else
        {
        }
        try 
        {
            Connection con=baglanti.getConnection();
                Statement st=con.createStatement();
                st.executeUpdate("INSERT INTO YGT.sikayetler (sikayet) VALUES ('"+sikayet+"')");
                JOptionPane.showMessageDialog(null, "Şikayetiniz iletilmiştir");
                dispose();
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Hata");
            e.printStackTrace();
        }
        
        girisEkrani gE= new girisEkrani();
        gE.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_gonderBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sikayetlerSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sikayetlerSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sikayetlerSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sikayetlerSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sikayetlerSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baslik;
    private javax.swing.JButton geriDonBtn;
    private javax.swing.JButton gonderBtn;
    private javax.swing.JScrollPane sikayetScroll;
    private javax.swing.JTextArea sikayetTXT;
    // End of variables declaration//GEN-END:variables
}
