/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphaneyonetim;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author yigit
 */
public class yeniKitap extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form uyeOlmaEkrani
     */
    public yeniKitap() {
        super ("Kitap Ekle");
        initComponents();
        conn=baglanti.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitapLBL = new javax.swing.JLabel();
        yazarLBL = new javax.swing.JLabel();
        basimLBL = new javax.swing.JLabel();
        dilLBL = new javax.swing.JLabel();
        kAd = new javax.swing.JTextField();
        basim = new javax.swing.JTextField();
        yAd = new javax.swing.JTextField();
        onaylaBtn = new javax.swing.JButton();
        geriDonBtn = new javax.swing.JButton();
        baslikLBL = new javax.swing.JLabel();
        turLBL = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        stokMiktariLBL = new javax.swing.JLabel();
        dilComboBox = new javax.swing.JComboBox<>();
        turComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kitapLBL.setText("Kitap Adı");

        yazarLBL.setText("Yazar Adı");

        basimLBL.setText("Basım Yılı");

        dilLBL.setText("Dil");

        onaylaBtn.setText("Onayla");
        onaylaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylaBtnActionPerformed(evt);
            }
        });

        geriDonBtn.setText("Geri Dön");
        geriDonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonBtnActionPerformed(evt);
            }
        });

        baslikLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        baslikLBL.setText("Kitap Ekle");

        turLBL.setText("Tür");

        stokMiktariLBL.setText("Stok Miktarı");

        dilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Türkçe", "İngilizce", "Almanca", "Fransızca", "İspanyolca", "Çince", "Rusça" }));

        turComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biyografi", "Deneme", "Dünya Klasikleri", "Dini", "Edebiyat", "Eğitim", "Felsefe", "Gezi", "Hikaye", "Kişisel Gelişim", "Macera", "Roman", "Siyasi", "Sözlük", "Şiir", "Tarih" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(geriDonBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(onaylaBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(basimLBL)
                                    .addComponent(dilLBL)
                                    .addComponent(turLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(turComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(basim, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(dilComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(stokMiktariLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(baslikLBL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kitapLBL)
                                            .addComponent(yazarLBL))
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yAd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kAd, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {basim, dilComboBox, kAd, stok, turComboBox, yAd});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baslikLBL)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitapLBL)
                    .addComponent(kAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yazarLBL)
                    .addComponent(yAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basimLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dilLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokMiktariLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onaylaBtn)
                    .addComponent(geriDonBtn))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onaylaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaylaBtnActionPerformed
        String mesaj;
       
        String kitapAd=kAd.getText();
        String yazarAd=yAd.getText();
        String basimYili=basim.getText();
        String dil=dilComboBox.getName();
        String tur=turComboBox.getName();
        String stokMiktari=stok.getText();
            try 
            {
                Connection con=baglanti.getConnection();
                Statement st=con.createStatement();
                st.executeUpdate("INSERT INTO YGT.kitap (kitapAd,yazarAd,basimYili,dil,tur,stokMiktari) VALUES('"+kitapAd+"','"+yazarAd+"','"+basimYili+"','"+dil+"','"+tur+"','"+stokMiktari+"')");
                JOptionPane.showMessageDialog(null, "Başarılı");
                new adminKutuphanesi().setVisible(true);
                dispose();
            } catch (Exception e) 
            {
               JOptionPane.showMessageDialog(null, "Hata");
               e.printStackTrace();
               /* setVisible(false);
                new uyeOlmaEkrani().setVisible(true);*/
            }
       /*
        //INSERT INTO kullanici (ad,soyad,sifre,yas,email,telefonNO,kimlikNO) values (?,?,?,?,?,?,?))
      //  pst=conn.prepareStatement(sql);
        pst.setString(1,ad.getText());
        pst.setString(2,soyad.getText());
        pst.setString(3,sifre.getText());
        pst.setString(4,yas.getText());
        pst.setString(5, telefonNO.getText());
        pst.setString(6,kimlikNO.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null, "Üyelik oluşturuldu");
        rs.close();
        pst.close();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        e.printStackTrace();
        System.out.println(pst);
    }    */

// TODO add your handling code here:
    }//GEN-LAST:event_onaylaBtnActionPerformed

    private void geriDonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonBtnActionPerformed
        setVisible(false);
        adminKutuphanesi aK= new adminKutuphanesi();
        aK.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_geriDonBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new yeniKitap().setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yeniKitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yeniKitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yeniKitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yeniKitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     //</ yazarLBLitor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yeniKitap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basim;
    private javax.swing.JLabel basimLBL;
    private javax.swing.JLabel baslikLBL;
    private javax.swing.JComboBox<String> dilComboBox;
    private javax.swing.JLabel dilLBL;
    private javax.swing.JButton geriDonBtn;
    private javax.swing.JTextField kAd;
    private javax.swing.JLabel kitapLBL;
    private javax.swing.JButton onaylaBtn;
    private javax.swing.JTextField stok;
    private javax.swing.JLabel stokMiktariLBL;
    private javax.swing.JComboBox<String> turComboBox;
    private javax.swing.JLabel turLBL;
    private javax.swing.JTextField yAd;
    private javax.swing.JLabel yazarLBL;
    // End of variables declaration//GEN-END:variables
}
